FROM python:3.10-slim
WORKDIR /app

# First, copy only the requirements.txt file and install the Python dependencies.
COPY requirements.txt .
RUN pip install -r requirements.txt

# Next it creates a enviroment variable letting flask know what route to pick for the db
ENV DOCKER=true
RUN echo $DOCKER

# Next, copy the entire project (including setup.py) into the container.
COPY . .

# Now, run pip install . This will install your project/package.
RUN pip install .

EXPOSE 2020
CMD ["python","-m", "run"]
